#!/bin/sh
set -e

if [ -z "$1" ]; then
  out_file="dist/checode"
else
  out_file="$1"
fi

envs="CGO_ENABLED=0 GOGC=off"
go_flags="-a -installsuffix nocgo -o $out_file"

rm -f dist/checode

# Build binary
env $envs go build $go_flags checode.go
