#!/bin/sh
if [ -z "$dockerhub_password" ]; then
  echo "\$dockerhub_password variable is not set"
  exit 1
fi
docker buildx create --driver-opt image=moby/buildkit:master
echo $dockerhub_password | docker login --username mishamyrt --password-stdin
docker buildx build \
  --push \
  --platform linux/amd64,linux/arm64 \
  --tag mishamyrt/checode:latest .
