name: build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build binaries
      run: make

    - name: Upload Darwin binary
      uses: actions/upload-artifact@v1
      with:
        name: macOS_binary
        path: dist/checode_darwin64

    - name: Upload Linux binary
      uses: actions/upload-artifact@v1
      with:
        name: linux_binary
        path: dist/checode_linux64

    - name: Upload Windows binary
      uses: actions/upload-artifact@v1
      with:
        name: windows_binary
        path: dist/checode_windows64.exe
